const roastPhrases = [
  'Xin Nhẹ Một Set',
  'Chưa Thua Trận Nào',
  'Thua Tại Sân Trơn',
  'Đập Nhẹ Thôi Mà',
  'Cầu Bay Vợt Gãy',
  'Đánh Vui Nhưng Không Nhường',
  'Vừa Khởi Động Đã Thắng',
  'Hôm Nay Tay Hơi Run',
  'Đội Bạn May Thôi',
  'Không Cay Chỉ Hơi Tức',
  'Đập Một Cái Là Xong',
  'Cứu Cầu Bằng Niềm Tin',
  'Vợt Này Mượn Nha',
  'Thắng Nhờ Phong Độ',
  'Thua Do Thiếu May Mắn',
  'Cầu Chạm Lưới Là Chiến Thuật',
  'Đứng Nhìn Cũng Ghi Điểm',
  'Đánh Nhẹ Mà Đối Thủ Mệt',
  'Không Mạnh Nhưng Lì',
  'Một Set Nữa Rồi Về',
  'Đừng Đập Vào Mặt',
  'Cầu Này Tính Không',
  'Trọng Tài Nhà Làm',
  'Ăn Điểm Bằng Khí Chất',
  'Đội Hình Hơi Mỏi',
  'Mới Tập Nhưng Rất Gắt',
  'Đánh Cho Ra Mồ Hôi',
  'Cầu Qua Là Mừng',
  'Giao Cầu Xong Cầu Nguyện',
  'Đập Hụt Nhưng Có Uy',
  'Phòng Thủ Bằng Ánh Mắt',
  'Cầu Cao Tới Nóc',
  'Đội Hình Không Bao Giờ Lỗi',
  'Thua Là Do Gió',
  'Thắng Là Do Trình',
  'Đánh Xong Đi Ăn',
  'Xin Đừng Bỏ Nhỏ',
  'Bỏ Nhỏ Nhưng Không Nhỏ Mọn',
  'Đập Cầu Như Đập Deadline',
  'Mệt Nhưng Vẫn Gáy',
  'Tay Yếu Nhưng Miệng Mạnh',
  'Đánh Ít Gáy Nhiều',
  'Cầu Lông Không Cầu May',
  'Đập Cầu Không Đập Bạn',
  'Đội Bạn Tự Thua',
  'Cầu Đi Đâu Không Biết',
  'Vợt Chỉ Đường Cầu Tự Đi',
  'Không Hay Nhưng Hên',
  'Hên Là Một Kỹ Năng',
  'Đội Hình Vô Tri',
  'Cú Đập Tình Thương',
  'Đập Nhẹ Sương Sương',
  'Cầu Qua Sân Là Thành Công',
  'Gãy Vợt Không Gãy Ý Chí',
  'Không Sợ Smash Chỉ Sợ Đói',
  'Còn Pin Là Còn Đánh',
  'Hết Pin Xin Nghỉ',
  'Đánh Tới Khi Đói',
  'Thắng Thì Gáy Thua Thì Im',
  'Đánh Vui Có Thưởng',
]

const roastPrefixes = [
  'Xin Nhẹ',
  'Chưa Thua',
  'Đập Nhẹ',
  'Giao Cầu',
  'Cứu Cầu',
  'Phòng Thủ',
  'Bỏ Nhỏ',
  'Đánh Vui',
  'Thắng Nhờ',
  'Thua Do',
  'Mới Tập',
  'Tay Yếu',
  'Không Hay',
  'Hơi Mỏi',
  'Vừa Khởi Động',
]

const roastSuffixes = [
  'Một Set',
  'Trận Nào',
  'Thôi Mà',
  'Xong Cầu Nguyện',
  'Bằng Niềm Tin',
  'Bằng Ánh Mắt',
  'Nhưng Không Nhỏ Mọn',
  'Nhưng Không Nhường',
  'Phong Độ',
  'Thiếu May Mắn',
  'Nhưng Rất Gắt',
  'Nhưng Miệng Mạnh',
  'Nhưng Hên',
  'Nhưng Vẫn Gáy',
  'Đã Thấy Mệt',
]

function randomItem<T>(items: readonly T[]): T {
  return items[Math.floor(Math.random() * items.length)]
}

export function generateVietnameseTeamName(): string {
  const patterns = [
    () => randomItem(roastPhrases),
    () => randomItem(roastPhrases),
    () => `${randomItem(roastPrefixes)} ${randomItem(roastSuffixes)}`,
  ]
  return randomItem(patterns)()
}
